### PR TITLE
Same app name different platform

### PR DESCRIPTION
**Pull request by ratmice**
I'm not sure if this is wanted, I was slightly confused trying to just change the `-DPLATFORM=x86`, until I noticed the `Arm/vm_minimal` vs `x86/minimal` difference.

This slightly simplifies the `settings.cmake` logic and allows apps to have the same name across different platforms.
The second patch renames minimal to vm_minimal, i'm less sure of this part, as there may be references outside of this repo in docs/etc?

Anyhow it seemed easy enough to do and could simplify the build instructions, however feel free to close if renaming stuff is undesirable for whatever reason.

### CODE REVIEW

**Comment by ratmice** [comment]
I now see why this won't work as is, because the Arm platforms, aren't named `Arm`, I'll leave this open for now though, it would be easy to switch to something like `-DARCH=Arm -DPLATFORM=tk1` or something to that effect..

**Comment by ratmice** [comment]
forgot to comment, but I updated this to address the issue noted above.

**Comment by oliver-wm** [comment]
Thanks for that!

**Comment by oliver-wm** [comment]
@ssrg-bamboo `test`

**Comment by ratmice** [comment]
@oliver-wm Just a gentle ping, because the bot never responded. Perhaps it isn't set up to watch this repo or something?

**Comment by oliver-wm** [comment]
This has been resolved in the camkes-vm-examples repo.

**Comment by ratmice** [comment]
@oliver-wm hmm, I don't see anything in the camkes-vm-examples the `settings.cmake` there _appears_ to be as it was before this patch, but I haven't tried it just looked at the source, I will try that repo out though, and assume any further patch should go there in the future.

**Pull request closed without merging**
